name: MIXER

on:
  workflow_dispatch:
    inputs:
      voice_url:
        description: 'URL mp3 файла голоса от ElevenLabs'
        required: true
  repository_dispatch:
    types: [mix_audio]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install ffmpeg & jq
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg jq

      - name: Read payload (voice url comes from Make or manual input)
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "{\"voice_url\": \"${{ github.event.inputs.voice_url }}\"}" > payload.json
          else
            echo '${{ toJson(github.event.client_payload) }}' > payload.json
          fi
          cat payload.json

      - name: Download input files
        env:
          INTRO_URL: ${{ secrets.INTRO_URL }}
          OUTRO_URL: ${{ secrets.OUTRO_URL }}
          BG_URL:    ${{ secrets.BG_URL }}
        run: |
          VOICE_URL=$(jq -r '.voice_url' payload.json)

          curl -L "$VOICE_URL" -o voice.mp3
          curl -L "$INTRO_URL" -o intro.mp3
          curl -L "$OUTRO_URL" -o outro.mp3
          curl -L "$BG_URL"    -o bg.mp3

      - name: Mix voice + background (loop bg, adjust volumes)
        env:
          BG_DB: "-18"     # громкость подложки
          VOICE_DB: "0"    # громкость голоса
        run: |
          ffmpeg -y -stream_loop -1 -i bg.mp3 -i voice.mp3 \
            -filter_complex "[0:a]volume=${BG_DB}dB[bg];[bg][1:a]amix=inputs=2:duration=shortest:dropout_transition=2[m];[m]volume=${VOICE_DB}dB[out]" \
            -map "[out]" -shortest -ar 44100 -b:a 128k voice_mix.mp3

      - name: Concatenate intro + mix + outro
        run: |
          printf "file 'intro.mp3'\nfile 'voice_mix.mp3'\nfile 'outro.mp3'\n" > list.txt
          ffmpeg -y -f concat -safe 0 -i list.txt -c copy result.mp3 || \
          ffmpeg -y -i intro.mp3 -i voice_mix.mp3 -i outro.mp3 \
            -filter_complex "[0:a][1:a][2:a]concat=n=3:v=0:a=1[out]" \
            -map "[out]" -ar 44100 -b:a 128k result.mp3

      - name: Upload to Cloudinary (unsigned preset)
        env:
          CLD_CLOUD_NAME:    ${{ secrets.CLD_CLOUD_NAME }}
          CLD_UPLOAD_PRESET: ${{ secrets.CLD_UPLOAD_PRESET }}
        run: |
          set -e
          if [ -z "$CLD_CLOUD_NAME" ] || [ -z "$CLD_UPLOAD_PRESET" ]; then
            echo "❌ Missing CLD_CLOUD_NAME or CLD_UPLOAD_PRESET secrets"; exit 1
          fi
          echo "✔ Uploading with unsigned preset '$CLD_UPLOAD_PRESET' to cloud '$CLD_CLOUD_NAME'"
          curl -sS -X POST "https://api.cloudinary.com/v1_1/$CLD_CLOUD_NAME/auto/upload" \
            -F file=@result.mp3 \
            -F upload_preset=$CLD_UPLOAD_PRESET \
            -F folder=prokis \
            -w "\nHTTP %{http_code}\n" \
            -o cld.json
          cat cld.json
          URL=$(jq -r '.secure_url // empty' cld.json)
          if [ -z "$URL" ] || [ "$URL" = "null" ]; then
            echo "❌ Cloudinary unsigned upload failed"; exit 1
          fi
          echo "FINAL_URL=$URL" >> $GITHUB_ENV
          echo "✅ Uploaded: $URL"

      - name: Callback to Make
        env:
          MAKE_CALLBACK_URL: ${{ secrets.MAKE_CALLBACK_URL }}
        run: |
          curl -fSL -X POST -H "Content-Type: application/json" \
            -d "{\"final_url\":\"$FINAL_URL\"}" "$MAKE_CALLBACK_URL"
